version: '3'

services:
  app:
    image: ias-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REQUIREMENTS_FILE=requirements.txt
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
